version: '3.8'
services:
  bot:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: voitra
    ports:
      - "443:443"
    restart: on-failure
    environment:
      BOT_TOKEN: $${{ secrets.BOT_TOKEN }}
      OPENAI_API_KEY: $${{ secrets.BOT_TOKEN }}
    volumes:
      - ~/Voitra/app/tracks:/bot/app/tracks
    # env_file:
    #   - ../.env
