version: '3.8'
services:
  bot:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
    container_name: voitra
    ports:
      - "443:443"
    # volumes:
    #   - ~/Voitra/app/tracks:/bot/app/tracks
    # env_file:
    #   - ../.env

# volumes:
#   - ~/Voitra/app/tracks:/bot/app/tracks