name: deploy

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploying using ssh
        uses: appleboy/ssh-action@master
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          password: ${{ secrets.PASS }}
          script: |
            cd Voitra
            git pull
