name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    env: 
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
      # - uses: actions/checkout@v4
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # password: ${{ secrets.PASS }}
          # envs: OPENAI_API_KEY,BOT_TOKEN
          script: |
            cd Voitra
            git pull origin main
            # echo BOT_TOKEN=${BOT_TOKEN} > Docker/.env
            # echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> Docker/.env 
            sudo docker compose -f Docker/docker-compose.yml up -d
